const story = (id, n, title, comments) => `
<tr class="athing submission" id="${id}"><td align="right" valign="top" class="title"><span class="rank">${n}.</span></td><td valign="top" class="votelinks"><center><a id="up_${id}" href="vote?id=${id}&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="titleline"><a href="https://example.com/${id}">${title}</a><span class="sitebit comhead"> (<a href="from?site=example.com"><span class="sitestr">example.com</span></a>)</span></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline"><span class="score" id="score_${id}">100 points</span> by <a href="user?id=bob" class="hnuser">bob</a> <span class="age" title="2026-10-05T10:00:00"><a href="item?id=${id}">2 hours ago</a></span> <span id="unv_${id}"></span> | <a href="hide?id=${id}&amp;goto=news">hide</a> | <a href="item?id=${id}">${comments}</a> </span></td></tr><tr class="spacer" style="height:5px"></tr>`;
const job = (id, n) => `<tr class="athing submission" id="${id}"><td align="right" valign="top" class="title"><span class="rank">${n}.</span></td><td></td><td class="title"><span class="titleline"><a href="https://jobs.example.com">Acme is hiring</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="age"><a href="item?id=${id}">3 hours ago</a></span> | <a href="hide?id=${id}">hide</a></td></tr><tr class="spacer" style="height:5px"></tr>`;
const head = `<html lang="en" op="news"><head><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef"><tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="https://news.ycombinator.com"><img src="y18.svg" width="18" height="18"></a></td><td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="news">Hacker News</a></b> <a href="newest">new</a> | <a href="front">past</a> | <a href="newcomments">comments</a></span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop"><a href="login?goto=news">login</a></span></td></tr></table></td></tr><tr id="bigbox"><td>`;
exports.front = head + `<table border="0" cellpadding="0" cellspacing="0">` +
  story(101, 1, "First story", "12&nbsp;comments") + story(102, 2, "Second story", "discuss") + job(103, 3) + story(104, 4, "Fourth story", "1&nbsp;comment") +
  `<tr class="morespace" style="height:10px"></tr><tr><td colspan="2"></td><td class="title"><a href="?p=2" class="morelink" rel="next">More</a></td></tr></table></td></tr></table></center></body></html>`;
const comment = (id, indent, user, text) => `<tr class="athing comtr" id="${id}"><td><table border="0"><tr><td class="ind" indent="${indent}"><img src="s.gif" height="1" width="${indent*40}"></td><td valign="top" class="votelinks"><center><a id="up_${id}" href="vote?id=${id}"><div class="votearrow"></div></a></center></td><td class="default"><div style="margin-top:2px; margin-bottom:-10px;"><span class="comhead"><a href="user?id=${user}" class="hnuser">${user}</a> <span class="age" title="x"><a href="item?id=${id}">1 hour ago</a></span> <span id="unv_${id}"></span><span class="navs"> | <a href="#" class="clicky">next</a> <a class="togg clicky" id="${id}" n="1" href="javascript:void(0)">[–]</a></span></span></div><br><div class="comment"><div class="commtext c00">${text}</div><div class="reply"><p><font size="1"><u><a href="reply?id=${id}">reply</a></u></font></p></div></div></td></tr></table></td></tr>`;
exports.item = head + `<table class="fatitem" border="0">` + story(101, 1, "First story", "4&nbsp;comments").replace(/<tr class="spacer"[^>]*><\/tr>/, '') +
  `<tr style="height:10px"></tr><tr><td colspan="2"></td><td><form action="comment" method="post"><textarea name="text"></textarea><br><input type="submit" value="add comment"></form></td></tr></table><br><table border="0" class="comment-tree">` +
  comment(201, 0, "alice", "Top one") + comment(202, 1, "bob", "Reply to alice") + comment(203, 2, "carol", "Reply to bob") + comment(204, 0, "dave", "Top two") +
  `</table><br><br></td></tr></table></center></body></html>`;
